version: '3.8'

services:
  # Backend API optimizado para desarrollo
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      cache_from:
        - comsigns-backend-fast
    image: comsigns-backend-fast
    container_name: comsigns-backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=dev-secret-key-change-in-production
      - SUPABASE_URL=https://xqdlbbwavnmkewvjaget.supabase.co
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxZGxiYndhdm5ta2V3dmphZ2V0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTUxNjksImV4cCI6MjA2ODY3MTE2OX0.MRfDvIbM8zOEwTj6muzZTzeNwWoQ-TfjzExjMIabLs4
      - SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxZGxiYndhdm5ta2V3dmphZ2V0Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MzA5NTE2OSwiZXhwIjoyMDY4NjcxMTY5fQ.gU5Z6p3gfa96UVOzPb72vU9J-0wjzb9B829WJaQOTuo
    volumes:
      - ./backend:/app:cached  # cached para mejor performance en macOS
      - ./backend/models:/app/models:cached
      - backend_cache:/root/.cache/pip  # Cache de pip persistente
    depends_on:
      - redis
    networks:
      - comsigns-network
    restart: unless-stopped
    # Optimizaciones para desarrollo
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=100m
  # Redis para cache y sesiones
  redis:
    image: redis:7-alpine
    container_name: comsigns-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - comsigns-network
    restart: unless-stopped
    # Optimizaciones para desarrollo
    command: >
      redis-server
      --appendonly yes
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --save 60 1000

volumes:
  redis_data:
    driver: local
  backend_cache:  # Cache persistente para pip
    driver: local

networks:
  comsigns-network:
    driver: bridge
